language: java

sudo: true

services:
  - docker

cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
os:
  - linux

branches:
  only:
    - master

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t flowingretail/checkout ./checkout/
  - docker push flowingretail/checkout
  - docker build -t flowingretail/order ./order/
  - docker push flowingretail/order
  - docker build -t flowingretail/payment ./payment/
  - docker push flowingretail/payment
  - docker build -t flowingretail/inventory ./inventory/
  - docker push flowingretail/inventory
  - docker build -t flowingretail/shipping ./shipping/
  - docker push flowingretail/shipping
  - docker build -t flowingretail/monitor ./monitor/
  - docker push flowingretail/monitor
  - docker build -t flowingretail/docs ./docs/
  - docker push flowingretail/docs